name: Verify and Merge Submission
'on':
  pull_request_target:
    types:
      - opened
      - synchronize
    paths:
      - submissions/**
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Verify Submission Hash
        env:
          CORRECT_ANSWERS_JSON: '${{ secrets.CORRECT_ANSWERS_JSON }}'
        run: python tools/verify_pr.py
      - name: Auto-merge PR
        if: success()
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_NUMBER: '${{ github.event.pull_request.number }}'
        run: |
          gh pr merge $PR_NUMBER --auto --squash --delete-branch
          echo "PR #${PR_NUMBER} has been automatically merged."
