name: Check Author

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'submissions/**'

jobs:
  check_authors:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install requests

      - name: Check Author for Security
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python tools/validate_pr_paths.py 

      - name: Notify PR about invalid file edits
        if: failure()
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --request POST \
            --data '{"body": "One or more files modified outside the allowed directory. Please modify files under directory named as your Github-Username only and re-submit the PR."}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - name: Close the PR
        if: failure()
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --request PATCH \
            --data '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"

